name: Trigger auto deployment for container-app-eifvaiicinyb4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/eShop.AppHost/**'
    - '.github/workflows/container-app-eifvaiicinyb4-AutoDeployTrigger-15a0bb9b-e386-48e5-846f-60b8abc67f91.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPEIFVAIICINYB4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPEIFVAIICINYB4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPEIFVAIICINYB4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/eShop.AppHost 
          registryUrl: containerregistryeifvaiicinyb4.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPEIFVAIICINYB4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPEIFVAIICINYB4_REGISTRY_PASSWORD }}
          containerAppName: container-app-eifvaiicinyb4
          resourceGroup: eshoponazure9970
          imageToBuild: containerregistryeifvaiicinyb4.azurecr.io/container-app-eifvaiicinyb4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


